# Django settings for irongate project.
#
# Generated by 'django-admin startproject' using Django 5.0.14.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/5.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.0/ref/settings/

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-$67g3a3b346ykw!k=96x#n0sc+q72h%#d$j8ee*q^&)0g&#_dz')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# RCON Encryption Key (loaded from environment)
RCON_ENCRYPTION_KEY = os.getenv('RCON_ENCRYPTION_KEY')

# Validate encryption key on startup
if RCON_ENCRYPTION_KEY:
    # Import here to avoid circular imports
    import sys
    # Only validate if not running migrations or other management commands that don't need encryption
    skip_validation_commands = ['makemigrations', 'migrate', 'collectstatic', 'compilemessages']
    should_validate = not any(cmd in sys.argv for cmd in skip_validation_commands)
    
    if should_validate:
        try:
            from servers.utils.key_validator import KeyValidator
            from servers.utils.file_security import check_env_file_permissions
            
            # Validate key format
            is_valid, error_message = KeyValidator.validate_key(RCON_ENCRYPTION_KEY)
            if not is_valid:
                print("\n" + "=" * 80)
                print("ENCRYPTION KEY VALIDATION FAILED")
                print("=" * 80)
                print(error_message)
                print("=" * 80 + "\n")
                raise ValueError("Invalid RCON_ENCRYPTION_KEY. See error message above.")
            else:
                # Only print success message in development
                if DEBUG:
                    print("✅ RCON encryption key validated successfully")
            
            # Check .env file permissions
            is_secure, warning = check_env_file_permissions()
            if not is_secure and warning:
                print("\n" + warning)
                # Don't fail startup, just warn
                
        except ImportError:
            # During initial setup, the servers app might not be available yet
            pass
else:
    raise ValueError(
        "RCON_ENCRYPTION_KEY must be set in environment variables or .env file.\n"
        "Run 'python generate_key.py' to generate a new encryption key."
    )

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF Protection - Add your domain here
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS', 
    'http://localhost:8000,http://127.0.0.1:8000'
).split(',')


# Application definition

INSTALLED_APPS = [
    # Local apps must be first to override other app templates
    'servers',
    
    # Jazzmin admin theme (must be before django.contrib.admin)
    'jazzmin',
    
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'django_htmx',
    'captcha',  # django-simple-captcha
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n language switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',  # HTMX support
]

ROOT_URLCONF = 'irongate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'servers.context_processors.version_context',  # Version display
            ],
        },
    },
]

WSGI_APPLICATION = 'irongate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # Default to Chinese, users can switch to English

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', 'Simplified Chinese'),
]

# Path to translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# ============================================================================
# Automatic Backup Configuration
# ============================================================================
# Enable/disable automatic database backups
ENABLE_AUTO_BACKUP = os.getenv('ENABLE_AUTO_BACKUP', 'False').lower() == 'true'

# Backup directory path
BACKUP_PATH = os.getenv('BACKUP_PATH', '/opt/mc_rcon/backups')

# Maximum number of backup files to retain (default: 5)
BACKUP_MAX_COUNT = int(os.getenv('BACKUP_MAX_COUNT', '5'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for efficient static file serving
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================ 
# Captcha Configuration
# ============================================================================ 

CAPTCHA_IMAGE_SIZE = (120, 50)
CAPTCHA_FONT_SIZE = 32
CAPTCHA_LETTER_ROTATION = (-35, 35)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#001100'
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'  # Math challenge
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)
CAPTCHA_TIMEOUT = 5  # Minutes

# Email Configuration (for registration)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Development: print to console
# For production, configure SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Registration Settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Can be 'mandatory', 'optional', or 'none'


# ============================================================================ 
# Django Jazzmin Configuration - Vercel Style
# Copyright © 2025 MoYuK1ng
# ============================================================================ 

JAZZMIN_SETTINGS = {
    # Site branding
    "site_title": "MC RCON Manager",
    "site_header": "MC RCON Manager",
    "site_brand": "MC RCON Manager",
    "site_logo": None,
    "login_logo": None,
    "site_icon": None,
    
    # Welcome text
    "welcome_sign": "Manage your Minecraft servers",
    
    # Copyright (no version number) - will be overridden by custom footer template
    "copyright": "MoYuK1ng",
    
    # Hide version number completely
    "show_version": False,
    "version": "",  # Empty version string
    
    # Search
    "search_model": ["auth.User", "servers.Server", "servers.WhitelistRequest"],
    
    # Top menu links
    "topmenu_links": [
        {"name": "User Dashboard", "url": "dashboard", "permissions": ["auth.view_user"], "icon": "fas fa-home"},
    ],
    
    # Custom links in sidebar
    "custom_links": {
        "servers": [{
            "name": "Ungrouped Users / 未分组用户", 
            "url": "admin:ungrouped_users", 
            "icon": "fas fa-user-slash",
            "permissions": ["auth.change_user"]
        }]
    },
    
    # User menu
    "usermenu_links": [
        {"name": "User Dashboard", "url": "dashboard", "icon": "fas fa-home"},
    ],
    
    # Side menu
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "servers.Server": "fas fa-server",
        "servers.WhitelistRequest": "fas fa-clipboard-list",
        "servers.Announcement": "fas fa-bullhorn",
    },
    
    # UI Builder
    "show_ui_builder": False,
    
    # Change form
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    
    # Language chooser (disabled - use site-wide language setting)
    "language_chooser": False,
    
    # Custom CSS
    "custom_css": "admin/css/custom_admin.css",
    
    # Custom JS
    "custom_js": "admin/js/custom_admin.js",
    
    # Related modal
    "related_modal_active": False,
}

JAZZMIN_UI_TWEAKS = {
    # Vercel-inspired color scheme
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",  # Clean, modern theme
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
}
