# Generated by Django 5.0.14 on 2025-11-28 06:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the Minecraft server', max_length=100, verbose_name='Server Name')),
                ('ip_address', models.GenericIPAddressField(help_text='IPv4 address of the Minecraft server', protocol='IPv4', verbose_name='IP Address')),
                ('rcon_port', models.IntegerField(default=25575, help_text='RCON port number (default: 25575)', verbose_name='RCON Port')),
                ('rcon_password_encrypted', models.BinaryField(help_text='Encrypted RCON password (never stored in plaintext)', verbose_name='Encrypted RCON Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='User groups that can access this server', related_name='servers', to='auth.group', verbose_name='Access Groups')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_username', models.CharField(help_text='Minecraft username to whitelist (3-16 alphanumeric characters and underscores)', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_minecraft_username', message='Username must be 3-16 characters long and contain only letters, numbers, and underscores', regex='^[a-zA-Z0-9_]{3,16}$')], verbose_name='Minecraft Username')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the whitelist request', max_length=10, verbose_name='Status')),
                ('response_log', models.TextField(blank=True, help_text='RCON server response or error message', verbose_name='Response Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('server', models.ForeignKey(help_text='Target Minecraft server', on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='Server')),
                ('user', models.ForeignKey(help_text='User who submitted the whitelist request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Whitelist Request',
                'verbose_name_plural': 'Whitelist Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
