# Generated by Django 5.0.14 on 2025-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title (supports Chinese and English)', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Announcement content (supports HTML formatting)', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, help_text='Only active announcements are displayed to users', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_ip_to_users', models.BooleanField(default=False, help_text='If enabled, users will see server IP addresses in the dashboard', verbose_name='Show IP Address to Users')),
                ('show_port_to_users', models.BooleanField(default=False, help_text='If enabled, users will see server ports in the dashboard', verbose_name='Show Port to Users')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Display Settings',
                'verbose_name_plural': 'Display Settings',
            },
        ),
    ]
