# Generated by Django 5.0.14 on 2025-11-29 11:28

from django.db import migrations


def create_default_display_settings(apps, schema_editor):
    """
    Create default DisplaySettings instance with secure defaults.
    By default, IP and port are hidden from users for security.
    """
    DisplaySettings = apps.get_model('servers', 'DisplaySettings')
    DisplaySettings.objects.get_or_create(
        pk=1,
        defaults={
            'show_ip_to_users': False,
            'show_port_to_users': False
        }
    )


def reverse_create_display_settings(apps, schema_editor):
    """
    Reverse migration: delete the DisplaySettings instance.
    """
    DisplaySettings = apps.get_model('servers', 'DisplaySettings')
    DisplaySettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_announcement_displaysettings'),
    ]

    operations = [
        migrations.RunPython(
            create_default_display_settings,
            reverse_create_display_settings
        ),
    ]
