# Generated by Django 5.0.14 on 2025-11-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_initialize_display_settings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whitelistrequest',
            unique_together={('server', 'minecraft_username')},
        ),
    ]
