# Generated by Django 5.0.14 on 2025-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_whitelistrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='game_ip',
            field=models.CharField(blank=True, help_text='IP or domain for players to connect (e.g., play.example.com)', max_length=255, verbose_name='Game Server IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='game_port',
            field=models.IntegerField(blank=True, default=25565, help_text='Port for players to connect (default: 25565)', null=True, verbose_name='Game Server Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IPv4 address for RCON connection (management only)', protocol='IPv4', verbose_name='RCON IP Address'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rcon_port',
            field=models.IntegerField(default=25575, help_text='RCON port number (default: 25575, management only)', verbose_name='RCON Port'),
        ),
    ]
