# Generated by Django 5.0.14 on 2025-11-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_add_game_server_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplaySettings',
        ),
    ]
