# Generated by Django 5.0.14 on 2025-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_remove_displaysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom metadata (modpack name, game version, description, etc.)', verbose_name='Custom Fields'),
        ),
    ]
